version: "3.5"
services:
  bot:
    build: .
    ports:
      - "8084:8084"
    restart: always
    volumes:
    - ./logs.txt:/usr/src/app/logs.txt
    depends_on:
      - redis_db_bot
      - database
  redis_db_bot:
    image: "redis:alpine"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6370:6379"
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    - ./redis/data:/data
#    - ./redis-server.log:/usr/local/etc/redis/redis-server.log

  database:
    container_name: postgres-bot
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_DB=crypto_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: