"""order_cost_fiat-add

Revision ID: 28900bd5090c
Revises: ff9947e95921
Create Date: 2021-05-31 01:06:37.878070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28900bd5090c'
down_revision = 'ff9947e95921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cost_fiat', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cost_fiat')
    # ### end Alembic commands ###
